# Generated by Django 5.2.3 on 2025-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The unique identifier for the tool (e.g., 'web_search'). Must match the tool's implementation filename in the tool_library.", max_length=100, unique=True)),
                ('description', models.TextField(help_text='A detailed description for the LLM to understand what the tool does, its purpose, and when to use it.')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, help_text="A JSON schema describing the parameters the tool's run() function expects. E.g., {'query': 'string'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
