# searxng/settings.yml - Completely open configuration for internal API use
use_default_settings: false

general:
  debug: true
  instance_name: "AIGENT Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

brand:
  new_issue_url: false
  docs_url: false
  public_instances: false
  wiki_url: false
  issue_url: false

search:
  safe_search: 0
  autocomplete: ""
  autocomplete_min: 2
  default_lang: "en"
  ban_time_on_fail: 0
  max_ban_time_on_fail: 0
  # CRITICAL: Disable all failure tracking
  suspended_times:
    SearxEngineAccessDenied: 0
    SearxEngineCaptcha: 0
    SearxEngineHTTPError: 0
    SearxEngineTooManyRequests: 0
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0:8080"
  secret_key: "your-secret-key-here"
  # CRITICAL: Completely disable rate limiting
  limiter: false
  public_instance: false
  image_proxy: false
  method: ["GET", "POST"]
  # Remove all security headers that might interfere
  default_http_headers: {}

ui:
  static_use_hash: false
  default_locale: "en"
  query_in_title: false
  infinite_scroll: false
  search_on_category_select: true
  hotkeys: false

# CRITICAL: Configure outgoing requests to be very permissive
outgoing:
  request_timeout: 15.0
  max_request_timeout: 30.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true
  # Use a realistic browser user agent
  default_user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  # CRITICAL: Allow requests from containers
  source_ips: []
  proxies: {}

# Configure engines with no restrictions
engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    timeout: 15.0
    disabled: false
    categories: [general, web]
    # Disable rate limiting for this engine
    using_tor_proxy: false
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    timeout: 15.0
    disabled: false
    categories: [general]

# Disable Redis completely
redis:
  url: false

categories_as_tabs:
  general: [general, web]

# CRITICAL: Add this section to disable bot detection
enabled_plugins: []
disabled_plugins:
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Unit converter plugin'