# Generated by Django 5.2.3 on 2025-06-14 18:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_state',
            field=models.JSONField(blank=True, default=users.models.get_default_user_state, help_text='Stores user-specific persistent state across sessions, modifiable by Aigents.', verbose_name='User Specific State'),
        ),
    ]
