# Generated by Django 5.2.3 on 2025-06-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="The user's IANA timezone name (e.g., 'America/New_York').", max_length=50),
        ),
    ]
