# Generated by Django 5.2.2 on 2025-06-04 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for this prompt template (e.g., 'StandardChatInteraction').", max_length=255, unique=True)),
                ('template_str', models.TextField(help_text='The full prompt string with placeholders like {system_persona_prompt}, {user_state}, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aigent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for this Aigent (e.g., 'LBA Support Aigent').", max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this Aigent is the currently active one for general user interaction. Only one should be active at a time.')),
                ('system_persona_prompt', models.TextField(blank=True, help_text="Brief description of the Aigent's role, personality, goals. This is a *part* of the full prompt.")),
                ('ollama_model_name', models.CharField(help_text="The Ollama model name to use (e.g., 'llama3:latest').", max_length=100)),
                ('ollama_endpoints', models.JSONField(default=list, help_text="A list of Ollama API base URLs for this Aigent (e.g., ['http://10.0.0.2:11434']).")),
                ('ollama_temperature', models.FloatField(blank=True, help_text='LLM temperature setting (optional). Controls randomness. Lower is more deterministic.', null=True)),
                ('ollama_context_length', models.IntegerField(blank=True, help_text='Context window size if configurable for the LLM (optional).', null=True)),
                ('aigent_state', models.JSONField(blank=True, default=dict, help_text="Stores the Aigent's own persistent state, modifiable by itself.", verbose_name='Aigent Specific State')),
                ('request_timeout_seconds', models.IntegerField(default=60, help_text='Timeout in seconds for requests to the Ollama server.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_prompt_template', models.ForeignKey(blank=True, help_text='The primary prompt template this Aigent uses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aigents', to='aigents.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.JSONField(default=list, help_text="Stores chat messages: [{'role': 'user/assistant', 'content': '...', 'timestamp': '...'}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aigent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='aigents.aigent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Histories',
                'unique_together': {('user', 'aigent')},
            },
        ),
    ]
