# Generated by Django 5.2.2 on 2025-06-07 20:01

import aigents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigent',
            name='presentation_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('raw', 'Raw Text')], default='markdown', help_text="The format for presenting the Aigent's responses in the UI (e.g., Markdown, HTML).", max_length=10),
        ),
        migrations.AlterField(
            model_name='aigent',
            name='aigent_state',
            field=models.JSONField(blank=True, default=aigents.models.get_default_aigent_state, help_text="Stores the Aigent's own persistent state, modifiable by itself.", verbose_name='Aigent Specific State'),
        ),
    ]
