# Generated by Django 5.2.3 on 2025-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigents', '0002_aigent_presentation_format_alter_aigent_aigent_state'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigent',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='The set of tools this Aigent is allowed to use.', to='tools.tool'),
        ),
    ]
